### ISSUE TITLE
[bug]: curl: (22) The requested URL returned error: 404

### ISSUE THREAD

**Issue by SPRATAY** [zdharma-continuum/zinit#581]
### What happened?

the same with adb and other plugins, as I understand them e file starting with _

### Steps to reproduce

➜  ~ zsh          

Setting up snippet: OMZP::ag
Downloading `OMZP::ag` (with curl, wget, lftp)...
curl: (22) The requested URL returned error: 404                                                                                                                                                                  
curl: (22) The requested URL returned error: 404                                                                                                                                                                  
ERROR: Download failed.
omz_termsupport_cwd:3: command not found: omz_urlencode

### Operating System & Version

OS: linux-gnu | Vendor: pc | Machine: x86_64 | CPU: x86_64 | Processor: AMD Ryzen 5 5600H with Radeon Graphics | Hardware: x86_64

### Zsh version

zsh 5.9 (x86_64-pc-linux-gnu)

### Terminal emulator

xterm-kitty

### If using WSL on Windows, which version of WSL

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vladdoster** [comment]
This is not a bug in Zinit, but due to `ag` plugin on being a completion. The syntax to handle this is covered in the [README.md](https://github.com/zdharma-continuum/zinit?tab=readme-ov-file#use-zi-ice-ascompletion-to-directly-add-single-file-completion-snippets)

```zsh
zi snippet OMZ::lib/functions.zsh
zi snippet OMZP::ag
```

or 

```zsh
zi as"completion" is-snippet for OMZP::ag/_ag
```

<img width="888" alt="Screenshot 2023-09-15 at 23 33 00" src="https://github.com/zdharma-continuum/zinit/assets/10052309/388e01e2-ec50-494d-9c4a-98e3fca0d96f">

**Comment by SPRATAY** [comment]
Thx bro(slava Ukraine)

**Comment by svenjacobs** [comment]
Thanks. This helped a lot! 👍🏼
